apiVersion: apps/v1
kind: Deployment
metadata:
  name: memorize-backend
  labels:
    app: memorize-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memorize-backend
  template:
    metadata:
      labels:
        app: memorize-backend
    spec:
      containers:
        - name: memorize-backend
          image: lertumpai/memorize-backend
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: memorize-backend-configmap
                  key: NODE_ENV
            - name: PRIVATE_KEY
              valueFrom:
                configMapKeyRef:
                  name: memorize-backend-configmap
                  key: PRIVATE_KEY
            - name: PRIVATE_HASH_KEY
              valueFrom:
                configMapKeyRef:
                  name: memorize-backend-configmap
                  key: PRIVATE_HASH_KEY
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: memorize-backend-configmap
                  key: MONGO_URI
            - name: SERVER_UPLOAD_URL
              valueFrom:
                configMapKeyRef:
                  name: memorize-backend-configmap
                  key: SERVER_UPLOAD_URL
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: memorize-backend-service
spec:
  type: ClusterIP
  selector:
    app: memorize-backend
  ports:
    - protocol: TCP
      port: 5000 # expose port
      targetPort: 5000
