apiVersion: apps/v1
kind: Deployment
metadata:
  name: memorize-backend
  labels:
    app: memorize-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memorize-backend
  template:
    metadata:
      labels:
        app: memorize-backend
    spec:
      containers:
        - name: memorize-backend
          image: lertumpai/memorize-backend
          env:
            - name: NODE_ENV
              value: "production"
            - name: PRIVATE_KEY
              value: "n@e#w$f%a^r&m*m(e)m_o+r1i2z3e4567890"
            - name: PRIVATE_HASH_KEY
              value: "$2b$10$OCSYVJ2HwOQ5iDA/U7ZjreK3OEdUzoCclByN0MPOkxy9UwPrJSW8m"
            - name: MONGO_URI
              value: "mongodb://lertumpai:sorawit5171718@192.168.1.106:27017/memorize"
            - name: SERVER_UPLOAD_URL
              value: "http://192.168.1.106:4000"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: memorize-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
