apiVersion: apps/v1
kind: Deployment
metadata:
  name: memorize-backend
  labels:
    app: memorize-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memorize-backend
  template:
    metadata:
      labels:
        app: memorize-backend
    spec:
      containers:
        - name: memorize-backend
          image: asia.gcr.io/wide-strength-304907/memorize-backend
          volumeMounts:
            - name: memorize-key-json
              mountPath: /gsa
              readOnly: true
          envFrom:
            - configMapRef:
                name: memorize-backend-configmap
          ports:
            - containerPort: 5000
      volumes:
        - name: memorize-key-json
          secret:
            secretName: memorize-key-json-secret
---
apiVersion: v1
kind: Service
metadata:
  name: memorize-backend-service
spec:
  type: ClusterIP
  selector:
    app: memorize-backend
  ports:
    - protocol: TCP
      port: 5000 # expose port
      targetPort: 5000
