version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    container_name: memorize_mongodb
    command: [--auth]
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/memorize_mongodb/

volumes:
  mongo_data:
    driver: local
