version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    container_name: memorize_mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/memorize_mongodb/
  memorize_upload:
    image: lertumpai/memorize-upload
    restart: always
    container_name: memorize_upload
    environment:
      - SERVER_URL=203.154.83.249:4000
      - TIME_OUT=300000
    command: npm run start
    ports:
      - 4000:4000
    volumes:
      - memorize_upload:/data/memorize_uploads/

volumes:
  memorize_upload:
    driver: local
  mongo_data:
    driver: local
