version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    container_name: memorize_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: lertumpai
      MONGO_INITDB_ROOT_PASSWORD: sorawit5171718
      MONGO_INITDB_DATABASE: memorize
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/memorize_mongodb/
  memorize_upload:
    image: lertumpai/memorize-upload
    restart: always
    container_name: memorize_upload
    environment:
      - SERVER_URL=35.247.128.57:4000
      - TIME_OUT=300000
    command: npm run start
    ports:
      - 4000:4000

volumes:
  mongo_data:
    driver: local
