version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    container_name: memorize_mongodb
    ports:
      - 27017:27017
    volumes:
      - database_data:/data/mongo/
  memorize_upload:
    image: lertumpai/memorize-upload
    restart: always
    container_name: memorize_upload
    command: npm run start
    ports:
      - 4000:4000
    volumes:
      - upload_data:/data/uploads/

volumes:
  upload_data:
    driver: local
  database_data:
    driver: local
