apiVersion: apps/v1
kind: Deployment
metadata:
  name: memorize-frontend
  namespace: ${MEMORIZE_NAMESPACE}
  labels:
    app: memorize-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memorize-frontend
  template:
    metadata:
      labels:
        app: memorize-frontend
    spec:
      containers:
        - name: memorize-frontend
          image: asia.gcr.io/wide-strength-304907/memorize-frontend:${MEMORIZE_DOCKER_TAG}
          envFrom:
            - configMapRef:
                name: memorize-frontend-configmap
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: memorize-frontend-service
spec:
  type: ClusterIP
  selector:
    app: memorize-frontend
  ports:
    - protocol: TCP
      port: 3000 # expose port
      targetPort: 3000
