apiVersion: apps/v1
kind: Deployment
metadata:
  name: memorize-upload
  labels:
    app: memorize-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memorize-upload
  template:
    metadata:
      labels:
        app: memorize-upload
    spec:
      containers:
        - name: memorize-upload
          image: asia.gcr.io/wide-strength-304907/memorize-upload
          envFrom:
            - configMapRef:
                name: memorize-upload-configmap
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: memorize-upload-service
spec:
  type: ClusterIP
  selector:
    app: memorize-upload
  ports:
    - protocol: TCP
      port: 4000 # expose port
      targetPort: 4000
