apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: nginx
spec:
  tls:
    - hosts:
        - memorize-nf.com
      secretName: memorize-tls
  rules:
    - host: memorize-nf.com
      http:
        paths:
          - path: /backend/(.*)
            backend:
              serviceName: memorize-backend-service
              servicePort: 5000
          - path: /(.*)
            backend:
              serviceName: memorize-frontend-service
              servicePort: 3000
