apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memorize-ingress
spec:
  rules:
    - http:
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: memorize-backend-service
                port:
                  number: 80
