apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: nginx
spec:
  rules:
    - http:
        paths:
          - path: /backend/(.*)
            backend:
              serviceName: memorize-backend-service
              servicePort: 5000
          - path: /(.*)
            backend:
              serviceName: memorize-frontend-service
              servicePort: 3000
