apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: nginx
spec:
  rules:
    - http:
        paths:
          - path: /backend(/|$)(.*)
            backend:
              serviceName: memorize-backend-service
              servicePort: 5000
